[
    Exposed=Window,
    DoNotCheckConstants
] interface VkConsts {
    const long VK_ENTER = 13;
    const long VK_LEFT = 37;
    const long VK_UP = 38;
    const long VK_RIGHT = 39;
    const long VK_DOWN = 40;
    const long VK_SPACE = 32;
    const long VK_BACK_SPACE = 8;
    const long VK_0 = 48;
    const long VK_1 = 49;
    const long VK_2 = 50;
    const long VK_3 = 51;
    const long VK_4 = 52;
    const long VK_5 = 53;
    const long VK_6 = 54;
    const long VK_7 = 55;
    const long VK_8 = 56;
    const long VK_9 = 57;
    const long VK_A = 65;
    const long VK_B = 66;
    const long VK_C = 67;
    const long VK_D = 68;
    const long VK_E = 69;
    const long VK_F = 70;
    const long VK_G = 71;
    const long VK_H = 72;
    const long VK_I = 73;
    const long VK_J = 74;
    const long VK_K = 75;
    const long VK_L = 76;
    const long VK_M = 77;
    const long VK_N = 78;
    const long VK_O = 79;
    const long VK_P = 80;
    const long VK_Q = 81;
    const long VK_R = 82;
    const long VK_S = 83;
    const long VK_T = 84;
    const long VK_U = 85;
    const long VK_V = 86;
    const long VK_W = 87;
    const long VK_X = 88;
    const long VK_Y = 89;
    const long VK_Z = 90;
    const long VK_RED = 403;
    const long VK_GREEN = 404;
    const long VK_YELLOW = 405;
    const long VK_BLUE = 406;
    const long VK_HELP = 47;
    const long VK_PLAY = 250;
    const long VK_PAUSE = 19;
    const long VK_PLAY_PAUSE = 179;
    const long VK_STOP = 178;
    const long VK_FAST_FWD = 228;
    const long VK_REWIND = 227;
    const long VK_BACK = 27;
    const long VK_CONTEXT_MENU = 93;
};
